import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import boundaries from "eslint-plugin-boundaries";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    plugins: { boundaries },
    settings: {
      "boundaries/elements": [
        { type: "domain", pattern: "src/domain/**" },
        { type: "application", pattern: "src/application/**" },
        { type: "infrastructure", pattern: "src/infrastructure/**" },
        { type: "presentation", pattern: "src/presentation/**" },
      ],
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        {
          default: "allow",
          policies: [
            {
              from: { element: { types: "domain" } },
              disallow: {
                to: {
                  element: {
                    types: { anyOf: ["application", "infrastructure", "presentation"] },
                  },
                },
              },
              message:
                "domain não pode importar de application, infrastructure ou presentation (ADR-005)",
            },
            {
              from: { element: { types: "application" } },
              disallow: { to: { element: { types: "presentation" } } },
              message: "application não pode importar de presentation (ADR-005)",
            },
            {
              from: { element: { types: "infrastructure" } },
              disallow: {
                to: { element: { types: { anyOf: ["application", "presentation"] } } },
              },
              message: "infrastructure não pode importar de application ou presentation (ADR-005)",
            },
            {
              from: { element: { types: "presentation" } },
              disallow: {
                to: { element: { types: { anyOf: ["domain", "infrastructure"] } } },
              },
              message:
                "presentation não pode importar diretamente de domain ou infrastructure — só de application (ADR-005)",
            },
          ],
        },
      ],
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  prettierConfig,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the test pyramid tooling (Stryker, Playwright):
    ".stryker-tmp/**",
    "reports/**",
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
